<?php
/**
 * MyBB 1.8 kurdish Language Pack
 * Copyright 2014 Mybb Group, SaM GoRAN
 * This Language Pack is free . It comes without any warranty to the extent permitted by applicable law.
 * You can redistribute it and/or modify it under the terms of the Do What The Fuck You Want To Public License.
 * Version 1.8.1 , as published by Sam GoRaN.
 * Contact to 'Cic4da@gmail.com' for more details.
 */
 
$l['nav_online'] = "ئامادەبوانی ئێستا";
$l['nav_onlinetoday'] = "ئاماده‌بوان له‌ 24 كاتژمێری ڕابردوو";

$l['viewing_announcements'] = "سەیری ئاگەدارییەکان <a href=\"{1}\">{2}</a> دەکات ";
$l['viewing_announcements2'] = "سەیری ئاگەدارییەکانی یانە دەکات";
$l['viewing_attachment'] = "سەیری هاوپێچ دەکات";
$l['viewing_attachment2'] = "يشاهد <a href=\"attachment.php?aid={1}\">المرفق</a> الموجود في موضوع <a href=\"{3}\">{2}</a></a>";
$l['viewing_calendar'] = "سەیری <a href=\"calendar.php\">ساڵنامە</a> دەکات ";
$l['viewing_event'] = "سەیری ڕووداو دەکات";
$l['viewing_event2'] = "سەیری ڕووداو <a href=\"{1}\">{2}</a> دەکات ";
$l['adding_event'] = "<a href=\"calendar.php?action=addevent\"> ڕووداوێکی نوێ زیاد دەکات</a>";
$l['editing_event'] = "دەستکاری ڕووداو دەکات";
$l['viewing_contact_us'] = "سەیری <a href=\"contact.php\">پەیوەندیمان پێوە بکە</a> دەکەت ";
$l['editing_post'] = "دەستکاری وەڵام دەکات";
$l['viewing_forum'] = "سەیری بەشێک دەکات";
$l['viewing_forum2'] = "سەیری بەشی <a href=\"{1}\">{2}</a> دەکات ";
$l['forum_redirect_to'] = "دەگوازرێتەوە بۆ <a href=\"{1}\">{2}</a>";
$l['viewing_index'] = "{1} <a href=\"index.php\">لاپەڕەی سەرەکی</a>";
$l['activating_account'] = "ڕاژە چاڵاک دەکات";
$l['viewing_profile'] = "سەیری پەڕەی تایبەتی دەکات";
$l['viewing_profile2'] = "سەیری پەڕەی <a href=\"{1}\">{2}</a> دەکات ";
$l['registering'] = "<a href=\"member.php?action=register\">خۆی تۆمار دەکات</a>";
$l['logging_in'] = "<a href=\"member.php?action=login\">دێتە ژوورەوە</a>";
$l['logging_in_plain'] = "دێتە ژوورەوە";
$l['logging_out'] = "دەچێتە دەرەوە";
$l['emailing_user'] = "پۆستی ئەلیکترۆنی دەنێرێت بۆ ئەندام";
$l['rating_user'] = "ئەندام هەلدەسەنگێنێت";
$l['viewing_memberlist'] = "سەیری <a href=\"memberlist.php\">لیستی هاوڕێیان</a> دەکات ";
$l['viewing_whoposted'] = "سەیری کێ وەڵامی داوە دەکات";
$l['viewing_whoposted2'] = "سەیری کێ وەڵامی داوە لە بابەت <a href=\"{1}\">{2}</a> دەکات ";
$l['marking_read'] = "<a href=\"misc.php?action=markread\">یانە وەک خوێندراو دیاری دەکات</a>";
$l['viewing_helpdocs'] = "سەیری <a href=\"misc.php?action=help\">بەڵگەنامەی یارمەتی</a> دەکات ";
$l['viewing_buddylist'] = "سەیری <a href=\"misc.php?action=buddypopup\">لیستی هاوڕێیان</a> دەکات ";
$l['viewing_smilies'] = "سەیری <a href=\"misc.php?action=smilies\">خەندەکان</a> دەکات ";
$l['viewing_syndication'] = "سەیری <a href=\"misc.php?action=syndication\">پوختەی Rss</a> دەکات ";
$l['replying_thread'] = "وەڵام بۆ بابەت دادەنێت";
$l['replying_thread2'] = "وەڵام دادەنێت لەبابەت <a href=\"{1}\">{2}</a> ";
$l['posting_thread'] = "بابەتی نوێ زیاد دەکات";
$l['posting_thread2'] = "بابەتی نوێ زیاد دەکات لە <a href=\"{1}\">{2}</a>";
$l['viewing_wol'] = "سەیری <a href=\"online.php\">ئامادەبوانی ئێستا</a> دەکات ";
$l['viewing_woltoday'] = "سەیری <a href=\"online.php?action=today\">ئاماده‌بوان له‌ 24 كاتژمێری ڕابردوو</a> دەکات ";
$l['creating_poll'] = "ڕاپرسیێکی نوێ زیاد دەکات";
$l['editing_poll'] = "دەستکاری ڕاپرسی دەکات";
$l['viewing_pollresults'] = "سەیری ئەنجامەکانی ڕاپرسی دەکات";
$l['voting_poll'] = "دەنگ بۆ ڕاپرسی زیاد دەکات";
$l['using_modtools'] = "ئامڕازەکانی سەرپەرشتی کردن بەکاردێنێت";
$l['sending_pm'] = "پەیامی تایبەتی دەنێرێت";
$l['reading_pm'] = "پەیامی تایبەتی دەخوێنێتەوە";
$l['editing_pmfolders'] = "دەستکاری بوخچەکانی پەیامی تایبەتی دەکات";
$l['using_pmsystem'] = "سیستەمی پەیامی تایبەتی بەکاردێنێت";
$l['reporting_post'] = "ئاگەدارکردنەوە دەدات لە بەشداری";
$l['searching_forum'] = "<a href=\"search.php\">هەلدەستێت بەگەڕان</a> {1}";
$l['reading_thread'] = "بابەت دەخوێنێتەوە";
$l['reading_thread2'] = "بابەت <a href=\"{1}\">{2}</a> {3} دەخوێنتەوە";
$l['viewing_team'] = "سەیری دەستەی بەڕێوەبران دەکات";
$l['viewing_stats'] = "سەیری سەرژمێرییەکانی یانە دەکات";
$l['updating_profile'] = "<a href=\"usercp.php?action=profile\">پەڕەی تایبەتی خۆی نوێ دەکاتەوە</a>";
$l['updating_options'] = "<a href=\"usercp.php?action=options\">هەلبژاردنەکان نوێ دەکاتەوە</a>";
$l['editing_signature'] = "<a href=\"usercp.php?action=editsig\">دەستکاری واژوو دەکات</a>";
$l['changing_avatar'] = "<a href=\"usercp.php?action=avatar\">وێنۆچکەی پەڕەی تایبەتی دەگۆڕێت</a>";
$l['viewing_subscriptions'] = "سەیری <a href=\"usercp.php?action=subscriptions\">هاوبەشییەکانی بابەت </a> دەکات ";
$l['viewing_favorites'] = "سەیری <a href=\"usercp.php?action=favorites\">بابەتە دلخوازەکان </a> دەکات ";
$l['editing_pad'] = "دەستکاری <a href=\"usercp.php?action=notepad\">تێبینی تایبەتی </a> دەکات ";
$l['editing_password'] = "دەستکاری <a href=\"usercp.php?action=password\">تێپەڕەوشە </a> دەکات ";
$l['user_cp'] = "سەیری <a href=\"usercp.php\">پەڕەی تایبەتی </a> دەکات ";
$l['viewing_portal'] = "سەیری <a href=\"portal.php\">دەروازە </a> دەکات ";
$l['viewing_noperms'] = "سەیری پەڕەی نەبونی دەسەلات دەکات";
$l['unknown_location'] = "<a href=\"{1}\">شوێنی نەناسراو</a>";
$l['giving_reputation'] = "پلە دەدات";
$l['viewing_reputation_report'] = "سەیری <a href=\"{1}\">{2}'s پلە </a> دەکات ";
$l['viewing_reputation_report2'] = "سەیری پلە دەکات";
$l['member_resendactivation'] = "دوبارە کۆدی چاڵاککردن دەنێرێت";
$l['member_lostpw'] = "دەگەڕێنێتەوە <a href=\"member.php?action=lostpw\">تێپەڕەوشەی لەیادکراو</a>";
$l['sending_thread'] = "بابەت دەنێرێت بۆ هاوڕێ";
$l['guest'] = "میوان";
$l['page'] = "پەڕە";
$l['users_online'] = "ئامادەبوانی ئێستا";
$l['on_username'] = "ناوی بەکارهێنەر";
$l['time'] = "کـات";
$l['location'] = "شـوێن";
$l['online_today'] = "ئامادەبوان لە 24 کاتژمێری ڕابردوو";
$l['refresh_page'] = "نوێ کردنەوە";
$l['online_online_plural'] = "بەکارهێنەر";
$l['online_online_singular'] = "بەکارهێنەر";
$l['online_member_plural'] = "ئەندام";
$l['online_member_singular'] = "ئەندام";
$l['online_anon_plural'] = "پێکهاتوە";
$l['online_anon_singular'] = "پێکهاتوە";
$l['online_guest_plural'] = "میوان";
$l['online_guest_singular'] = "میوان";
$l['online_count'] = "{1} {2} ئامادەبوەکان له‌ {3} كاتژمێری ڕابردوو ( {4} {5}،  {6} نادیار ، و {8} {9} ).";
$l['ip'] = "ئای پی :";
$l['resolves_to'] = "دەنگ دان :";
$l['if_resolvable'] = "(ئەگەر چارەسەر کرا)";
$l['admin_options'] = "هەلبژاردنەکانی بەڕێوەبەر :";
$l['search_regip_users'] = "گەڕان بەدوای بەکارهێنەرانی تۆماربوو بە هەمان ناونیشانی ئای پی .";
$l['search_postip_users'] = "گەڕان بەدوای ئەو ئەندامانەی کەبەشدارییان کردوە بە هەمان ئای پی";
$l['lookup'] = "[گەڕان]";
$l['member_online_today'] = "<strong>1</strong> ئەندام ئامادەبوو ئەمڕۆ";
$l['members_were_online_today'] = "<strong>{1}</strong> ئەندامە ئامادەبوەکان لەماوەی 24 کاتژمێر";
$l['member_online_hidden'] = " ({1} ئەندامی سەرهێل)";
$l['members_online_hidden'] = " ({1} ئەندامی دەرهێل)";
$l['rating_thread'] = "بابەت هەلدەسەنگێنێت";
$l['viewing_imcenter'] = "سەیری ناوەندی IM دەکات";
$l['managing_favorites'] = "بابەتە دلخوازەکان ڕێك دەخات";
$l['managing_subscriptions'] = "هاوبەشی لەبابەتەکان ڕێك دەخات";
$l['managing_group'] = "گروپی ئەندامان ڕێك دەخات";
$l['viewing_modcp'] = "سەیری پەڕەی تایبەتی سەرپەرشتیاران دەکات";
$l['viewing_modlogs'] = "سەیری تۆماری سەرپەرشتیاران دەکات";
$l['managing_announcements'] = "ئاگەدارییەکان ڕێك دەخات";
$l['search_for_user'] = "بەدوای بەکارهێنەر دەگەڕێت";
$l['managing_warninglogs'] = "تۆماری ئاگەدارییەکان ڕێك دەخات";
$l['searching_ips'] = "بەدای ناونیشانەکانی ئای پی دەگەڕێت";
$l['viewing_reports'] = "سەیری ئەو بەشدارییانە دەکات کە لێ ئاگەدار کراوەتەوە ";
$l['adding_announcement'] = "ئاگەداری نوێ زیاد دەکات";
$l['deleting_announcement'] = "ئاگەدارییەکانی یانە دەسڕێنێتەوە";
$l['editing_announcement'] = "یەکێک لە ئاگەدارییەکانی یانە دەسکاری دەکات";
$l['managing_modqueue'] = "بەڕێوەبرایەتی سەرپەرشتی کردن ڕێك دەخات";
$l['editing_user_profiles'] = "دەستکاری پەڕەی یەکێک لە ئەندامان دەکات";
$l['managing_bans'] = "قەدەغەکراوەکان بەڕێوەدەبات";
$l['revoking_warning'] = "ئاگەداری لا دەبات";
$l['warning_user'] = "ئەندام ئاگەدار دەکاتەوە";
$l['viewing_warning'] = "سەیری ئاگەدارییەکان دەکات";
$l['managing_warnings'] = "ئاگەدارییەکان بەڕێوە دەبات";
$l['changing_dst'] = "دەستکاری ڕێکخستنی کات دەکات";
$l['printing_thread'] = "بابەت چاپ دەکات";
$l['printing_thread2'] = "بابەت  <a href=\"{1}\">{2}</a> چاپ دەکات ";
$l['managing_buddyignorelist'] = "دەستکاری لیستی هاوڕێیان دەکات";
